services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./instance:/app/instance
      - ./app.py:/app/app.py:ro
      - ./api_utils.py:/app/api_utils.py:ro
      - ./anthropic_patch.py:/app/anthropic_patch.py:ro
      - ./services:/app/services:ro
    restart: unless-stopped
    networks:
      - matcha-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - matcha-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/app/uploads:ro
      - ./outputs:/app/outputs:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - matcha-network

networks:
  matcha-network:
    driver: bridge

volumes:
  redis-data: